### ISSUE TITLE
Layout of Candidate Detail Pages

### ISSUE THREAD

**Issue by griffin-h** [SAGUARO-MMA/saguaro_tom#1]
We all should think about what information we want to see on the candidate pages in order to make a decision about whether to "promote" the candidate, whether to schedule follow-up, when to rule it out, etc. A lot of this will be the diagnostics from @jrastinejad's paper. Probably also image subtraction triplets, in the case of SAGUARO candidates.

**Comment by dsand** [comment]
[Research Notes 10.pdf](https://github.com/SAGUARO-MMA/saguaro-tom/files/8633236/Research.Notes.10.pdf)

**Comment by dsand** [comment]
@jrastinejad is learning django!

**Comment by griffin-h** [comment]
@dsand would like the photometry tab to show up when you first load the page.

**Comment by jrastinejad** [comment]
Great, will do!

**Comment by griffin-h** [comment]
I made the photometry tab the default. I think we have most of the features we originally wanted on the target detail page now, so I'm closing this issue. There may be other things that come up, but we should make separate issues for them, instead of keeping this broad issue open forever.
