### ISSUE TITLE
Use local versions of the TNS and ZTF alert stream instead of the TOM broker infrastructure

### ISSUE THREAD

**Issue by griffin-h** [SAGUARO-MMA/saguaro_tom#5]
@pndaly is already keeping a copy of the TNS on SASSyII, which I should probably use for crossmatching instead of querying the TNS via the TOM broker infrastructure. I'm not sure exactly how to do this yet, and it will depend on successfully implementing Issue #2.

**Comment by pndaly** [comment]
You can reference the TNS records the same way Jillian references the milliquas, asassn records. In another issue,
I reported on sassy_q3c_models which are part of the way to using PyPI. The TNS code is in there and you can use it
the same way:

from sassy_q3c_models import *
from sassy_q3c_models.tns_q3c_orm import TnsQ3cRecord
from sassy_q3c_models.tns_q3c_orm_filters import tns_q3c_orm_filters

the same for ZTF:

from sassy_q3c_models import *
from sassy_q3c_models.ztf_q3c_orm import ZtfQ3cRecord
from sassy_q3c_models.ztf_q3c_orm_filters import ztf_q3c_orm_filters
