### ISSUE TITLE
Thoughts on non-localized events page

### ISSUE THREAD

**Issue by dsand** [SAGUARO-MMA/saguaro_tom#55]
1. Add link to Treasure Map.
2. Better visualization of localization on sky, big enough so we could overplot our own pointings.
3. Let's start including 'serendipitous' pointings taken by CSS up to 5(?) nights after an alert.  And start ingesting candidates from them.  it would good to start working out how these work and how candidates look.

**Comment by griffin-h** [comment]
These have all been completed, but on different pages. Point 1 is on the GW event list page, and points 2 and 3 are on the survey observations/candidates pages. Closing this for now, but we should make new issues if there are specific suggestions for how to rearrange these.
