### ISSUE TITLE
Variable time for ATLAS non-detection button

### ISSUE THREAD

**Issue by dsand** [SAGUARO-MMA/saguaro_tom#62]
Right now the ATLAS non-detection button will search the last 200 days.  This takes quite a while.  Suggestion is to add in a field to specify how many days to go back, with a default of 1-week or something similar.

**Comment by griffin-h** [comment]
I opened a PR for the first step, of adding that parameter to the function that calls the forced photometry: https://github.com/SAGUARO-MMA/kne-cand-vetting/pull/13. We still need to add the textbox to the UI to accept this parameter.

**Comment by griffin-h** [comment]
The TOM Toolkit now has ATLAS forced photometry [built in](https://tom-toolkit.readthedocs.io/en/latest/managing_data/forced_photometry.html), including a configurable date range. We need to look into how this gets processed and stored to make sure it matches what we're currently doing, but ultimately it's probably a better approach to use what they have than to modify what we have.

**Comment by dsand** [comment]
I'm not sure what else to say here.  We should either modify our approach for the ATLAS forced photometry button (having options for different time periods), or adopt what is in the TOM Toolkit now.  Before we adopt the TOM Toolkit version, though, we should make sure it works as we desire.

**Comment by jrastinejad** [comment]
Perhaps we talk about this on Thursday? Can add to the agenda. Off the bat I'm not sure how to test this myself

**Comment by griffin-h** [comment]
Resolved by #89
