### ISSUE TITLE
Target update does not work

### ISSUE THREAD

**Issue by dsand** [SAGUARO-MMA/saguaro_tom#63]
When I try to update a target (say, add a distance) it does not work.  Response is:

Target with Name or alias similar to SSS23a already exists

**Comment by griffin-h** [comment]
I opened an issue: https://github.com/TOMToolkit/tom_base/issues/663

**Comment by griffin-h** [comment]
We traced this back to a bug in the TOM Toolkit. Just waiting for the next release before testing and closing this issue. Probably after the holiday next week.
