### ISSUE TITLE
Bugfix: Correct DATETIME_FORMAT to show minute not month.

### ISSUE THREAD

**Issue by jchate6** [SAGUARO-MMA/saguaro_tom#78]
An [issue](https://github.com/TOMToolkit/tom_base/pull/778) has been discovered in the setup for tomtoolkit that mistakenly sets 
```Python
DATETIME_FORMAT = 'Y-m-d H:m:s'
```
in `settings.py`.
This code incorrectly used `m` (month) instead of `i` (minute) in the time format.

We are deploying a release to tomtoolkit that will correct this bug for future TOMs, but you will need to edit [this line](https://github.com/SAGUARO-MMA/saguaro_tom/blob/b2e812c849ddbc646deef6ef4a7af39a0eac65c2/saguaro_tom/settings.py#L163) .in your `settings.py`

**Comment by griffin-h** [comment]
Thanks @jchate6!
