### ISSUE TITLE
Units and significant digits in point source match panel for targets

### ISSUE THREAD

**Issue by dsand** [SAGUARO-MMA/saguaro_tom#90]
The panel below is great but can we a) put in units for the Gaia offset (presumably it is arcsec or ") and b) cut down on the number of significant digits.  

This is a minor tweak.
![Screen Shot 2024-04-13 at 1 00 02 PM](https://github.com/SAGUARO-MMA/saguaro_tom/assets/9013064/ad7bbf89-879f-49b2-8740-7a28b27c56f4)

**Comment by griffin-h** [comment]
Closed by #92
